// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Video annotation request.
public struct AnnotateVideoRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Input video location. Currently, only
  /// [Cloud Storage](https://cloud.google.com/storage/) URIs are
  /// supported. URIs must be specified in the following format:
  /// `gs://bucket-id/object-id` (other URI formats return
  /// [google.rpc.Code.INVALID_ARGUMENT][google.rpc.Code.INVALID_ARGUMENT]). For
  /// more information, see [Request
  /// URIs](https://cloud.google.com/storage/docs/request-endpoints). To identify
  /// multiple videos, a video URI may include wildcards in the `object-id`.
  /// Supported wildcards: '*' to match 0 or more characters;
  /// '?' to match 1 character. If unset, the input video should be embedded
  /// in the request as `input_content`. If set, `input_content` must be unset.
  public var inputUri: Swift.String = Swift.String()

  /// The video data bytes.
  /// If unset, the input video(s) should be specified via the `input_uri`.
  /// If set, `input_uri` must be unset.
  public var inputContent: Foundation.Data = Foundation.Data()

  /// Required. Requested video annotation features.
  public var features: [Feature] = []

  /// Additional video context and/or feature-specific parameters.
  public var videoContext: VideoContext? = nil

  /// Optional. Location where the output (in JSON format) should be stored.
  /// Currently, only [Cloud Storage](https://cloud.google.com/storage/)
  /// URIs are supported. These must be specified in the following format:
  /// `gs://bucket-id/object-id` (other URI formats return
  /// [google.rpc.Code.INVALID_ARGUMENT][google.rpc.Code.INVALID_ARGUMENT]). For
  /// more information, see [Request
  /// URIs](https://cloud.google.com/storage/docs/request-endpoints).
  public var outputUri: Swift.String = Swift.String()

  /// Optional. Cloud region where annotation should take place. Supported cloud
  /// regions are: `us-east1`, `us-west1`, `europe-west1`, `asia-east1`. If no
  /// region is specified, the region will be determined based on video file
  /// location.
  public var locationId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AnnotateVideoRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AnnotateVideoRequest().with { $0.inputUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let inputUri = CodingKeys(stringValue: "inputUri")
    static let inputContent = CodingKeys(stringValue: "inputContent")
    static let features = CodingKeys(stringValue: "features")
    static let videoContext = CodingKeys(stringValue: "videoContext")
    static let outputUri = CodingKeys(stringValue: "outputUri")
    static let locationId = CodingKeys(stringValue: "locationId")

    static let _knownKeys: Set<Swift.String> = [
      "inputUri",
      "inputContent",
      "features",
      "videoContext",
      "outputUri",
      "locationId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inputUri) {
      self.inputUri = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .inputContent) {
      self.inputContent = value
    }
    if let value = try container.decodeIfPresent([Feature].self, forKey: .features) {
      self.features = value
    }
    self.videoContext = try container.decodeIfPresent(VideoContext.self, forKey: .videoContext)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .outputUri) {
      self.outputUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .locationId) {
      self.locationId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.inputUri, forKey: .inputUri)
    try container.encode(self.inputContent, forKey: .inputContent)
    try container.encode(self.features, forKey: .features)
    try container.encodeIfPresent(self.videoContext, forKey: .videoContext)
    try container.encode(self.outputUri, forKey: .outputUri)
    try container.encode(self.locationId, forKey: .locationId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.AnnotateVideoRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
