// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Config for FACE_DETECTION.
public struct FaceDetectionConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Model to use for face detection.
  /// Supported values: "builtin/stable" (the default if unset) and
  /// "builtin/latest".
  public var model: Swift.String = Swift.String()

  /// Whether bounding boxes are included in the face annotation output.
  public var includeBoundingBoxes: Swift.Bool = Swift.Bool()

  /// Whether to enable face attributes detection, such as glasses, dark_glasses,
  /// mouth_open etc. Ignored if 'include_bounding_boxes' is set to false.
  public var includeAttributes: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `FaceDetectionConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FaceDetectionConfig().with { $0.model = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.FaceDetectionConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
