// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Deprecated. No effect.
@available(*, deprecated)
public struct FaceFrame: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Normalized Bounding boxes in a frame.
  /// There can be more than one boxes if the same face is detected in multiple
  /// locations within the current frame.
  public var normalizedBoundingBoxes: [NormalizedBoundingBox] = []

  /// Time-offset, relative to the beginning of the video,
  /// corresponding to the video frame for this location.
  public var timeOffset: GoogleCloudWKT.Duration? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `FaceFrame`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FaceFrame().with { $0.normalizedBoundingBoxes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let normalizedBoundingBoxes = CodingKeys(stringValue: "normalizedBoundingBoxes")
    static let timeOffset = CodingKeys(stringValue: "timeOffset")

    static let _knownKeys: Set<Swift.String> = [
      "normalizedBoundingBoxes",
      "timeOffset",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [NormalizedBoundingBox].self, forKey: .normalizedBoundingBoxes)
    {
      self.normalizedBoundingBoxes = value
    }
    self.timeOffset = try container.decodeIfPresent(
      GoogleCloudWKT.Duration.self, forKey: .timeOffset)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.normalizedBoundingBoxes, forKey: .normalizedBoundingBoxes)
    try container.encodeIfPresent(self.timeOffset, forKey: .timeOffset)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.FaceFrame"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
