// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Video annotation feature.
public enum Feature: Codable, Equatable, Sendable {
  /// Unspecified.
  case unspecified
  /// Label detection. Detect objects, such as dog or flower.
  case labelDetection
  /// Shot change detection.
  case shotChangeDetection
  /// Explicit content detection.
  case explicitContentDetection
  /// Human face detection.
  case faceDetection
  /// Speech transcription.
  case speechTranscription
  /// OCR text detection and tracking.
  case textDetection
  /// Object detection and tracking.
  case objectTracking
  /// Logo detection, tracking, and recognition.
  case logoRecognition
  /// Person detection.
  case personDetection
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .labelDetection: return 1
    case .shotChangeDetection: return 2
    case .explicitContentDetection: return 3
    case .faceDetection: return 4
    case .speechTranscription: return 6
    case .textDetection: return 7
    case .objectTracking: return 9
    case .logoRecognition: return 12
    case .personDetection: return 14
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "FEATURE_UNSPECIFIED"
    case .labelDetection: return "LABEL_DETECTION"
    case .shotChangeDetection: return "SHOT_CHANGE_DETECTION"
    case .explicitContentDetection: return "EXPLICIT_CONTENT_DETECTION"
    case .faceDetection: return "FACE_DETECTION"
    case .speechTranscription: return "SPEECH_TRANSCRIPTION"
    case .textDetection: return "TEXT_DETECTION"
    case .objectTracking: return "OBJECT_TRACKING"
    case .logoRecognition: return "LOGO_RECOGNITION"
    case .personDetection: return "PERSON_DETECTION"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Feature/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "FEATURE_UNSPECIFIED": self = .unspecified
    case "LABEL_DETECTION": self = .labelDetection
    case "SHOT_CHANGE_DETECTION": self = .shotChangeDetection
    case "EXPLICIT_CONTENT_DETECTION": self = .explicitContentDetection
    case "FACE_DETECTION": self = .faceDetection
    case "SPEECH_TRANSCRIPTION": self = .speechTranscription
    case "TEXT_DETECTION": self = .textDetection
    case "OBJECT_TRACKING": self = .objectTracking
    case "LOGO_RECOGNITION": self = .logoRecognition
    case "PERSON_DETECTION": self = .personDetection
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Feature/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .labelDetection
    case 2: self = .shotChangeDetection
    case 3: self = .explicitContentDetection
    case 4: self = .faceDetection
    case 6: self = .speechTranscription
    case 7: self = .textDetection
    case 9: self = .objectTracking
    case 12: self = .logoRecognition
    case 14: self = .personDetection
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .labelDetection: return try container.encode(1)
    case .shotChangeDetection: return try container.encode(2)
    case .explicitContentDetection: return try container.encode(3)
    case .faceDetection: return try container.encode(4)
    case .speechTranscription: return try container.encode(6)
    case .textDetection: return try container.encode(7)
    case .objectTracking: return try container.encode(9)
    case .logoRecognition: return try container.encode(12)
    case .personDetection: return try container.encode(14)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
