// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Config for LABEL_DETECTION.
public struct LabelDetectionConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// What labels should be detected with LABEL_DETECTION, in addition to
  /// video-level labels or segment-level labels.
  /// If unspecified, defaults to `SHOT_MODE`.
  public var labelDetectionMode: LabelDetectionMode = LabelDetectionMode()

  /// Whether the video has been shot from a stationary (i.e., non-moving)
  /// camera. When set to true, might improve detection accuracy for moving
  /// objects. Should be used with `SHOT_AND_FRAME_MODE` enabled.
  public var stationaryCamera: Swift.Bool = Swift.Bool()

  /// Model to use for label detection.
  /// Supported values: "builtin/stable" (the default if unset) and
  /// "builtin/latest".
  public var model: Swift.String = Swift.String()

  /// The confidence threshold we perform filtering on the labels from
  /// frame-level detection. If not set, it is set to 0.4 by default. The valid
  /// range for this threshold is [0.1, 0.9]. Any value set outside of this
  /// range will be clipped.
  /// Note: For best results, follow the default threshold. We will update
  /// the default threshold everytime when we release a new model.
  public var frameConfidenceThreshold: Swift.Float = Swift.Float()

  /// The confidence threshold we perform filtering on the labels from
  /// video-level and shot-level detections. If not set, it's set to 0.3 by
  /// default. The valid range for this threshold is [0.1, 0.9]. Any value set
  /// outside of this range will be clipped.
  /// Note: For best results, follow the default threshold. We will update
  /// the default threshold everytime when we release a new model.
  public var videoConfidenceThreshold: Swift.Float = Swift.Float()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LabelDetectionConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LabelDetectionConfig().with { $0.labelDetectionMode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let labelDetectionMode = CodingKeys(stringValue: "labelDetectionMode")
    static let stationaryCamera = CodingKeys(stringValue: "stationaryCamera")
    static let model = CodingKeys(stringValue: "model")
    static let frameConfidenceThreshold = CodingKeys(stringValue: "frameConfidenceThreshold")
    static let videoConfidenceThreshold = CodingKeys(stringValue: "videoConfidenceThreshold")

    static let _knownKeys: Set<Swift.String> = [
      "labelDetectionMode",
      "stationaryCamera",
      "model",
      "frameConfidenceThreshold",
      "videoConfidenceThreshold",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      LabelDetectionMode.self, forKey: .labelDetectionMode)
    {
      self.labelDetectionMode = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .stationaryCamera) {
      self.stationaryCamera = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .model) {
      self.model = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Float.self, forKey: .frameConfidenceThreshold)
    {
      self.frameConfidenceThreshold = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Float.self, forKey: .videoConfidenceThreshold)
    {
      self.videoConfidenceThreshold = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.labelDetectionMode, forKey: .labelDetectionMode)
    try container.encode(self.stationaryCamera, forKey: .stationaryCamera)
    try container.encode(self.model, forKey: .model)
    try container.encode(self.frameConfidenceThreshold, forKey: .frameConfidenceThreshold)
    try container.encode(self.videoConfidenceThreshold, forKey: .videoConfidenceThreshold)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.LabelDetectionConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
