// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Label annotation.
public struct LabelAnnotation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Detected entity.
  public var entity: Entity? = nil

  /// Common categories for the detected entity.
  /// For example, when the label is `Terrier`, the category is likely `dog`. And
  /// in some cases there might be more than one categories e.g., `Terrier` could
  /// also be a `pet`.
  public var categoryEntities: [Entity] = []

  /// All video segments where a label was detected.
  public var segments: [LabelSegment] = []

  /// All video frames where a label was detected.
  public var frames: [LabelFrame] = []

  /// Feature version.
  public var version: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LabelAnnotation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LabelAnnotation().with { $0.entity = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let entity = CodingKeys(stringValue: "entity")
    static let categoryEntities = CodingKeys(stringValue: "categoryEntities")
    static let segments = CodingKeys(stringValue: "segments")
    static let frames = CodingKeys(stringValue: "frames")
    static let version = CodingKeys(stringValue: "version")

    static let _knownKeys: Set<Swift.String> = [
      "entity",
      "categoryEntities",
      "segments",
      "frames",
      "version",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.entity = try container.decodeIfPresent(Entity.self, forKey: .entity)
    if let value = try container.decodeIfPresent([Entity].self, forKey: .categoryEntities) {
      self.categoryEntities = value
    }
    if let value = try container.decodeIfPresent([LabelSegment].self, forKey: .segments) {
      self.segments = value
    }
    if let value = try container.decodeIfPresent([LabelFrame].self, forKey: .frames) {
      self.frames = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
      self.version = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.entity, forKey: .entity)
    try container.encode(self.categoryEntities, forKey: .categoryEntities)
    try container.encode(self.segments, forKey: .segments)
    try container.encode(self.frames, forKey: .frames)
    try container.encode(self.version, forKey: .version)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.LabelAnnotation"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
