// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Normalized bounding box.
/// The normalized vertex coordinates are relative to the original image.
/// Range: [0, 1].
public struct NormalizedBoundingBox: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Left X coordinate.
  public var `left`: Swift.Float = Swift.Float()

  /// Top Y coordinate.
  public var top: Swift.Float = Swift.Float()

  /// Right X coordinate.
  public var `right`: Swift.Float = Swift.Float()

  /// Bottom Y coordinate.
  public var bottom: Swift.Float = Swift.Float()

  /// Initialize a new instance of `NormalizedBoundingBox`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NormalizedBoundingBox().with { $0.`left` = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case `left` = "left"
    case top = "top"
    case `right` = "right"
    case bottom = "bottom"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.`left` = try container.decode(Swift.Float.self, forKey: .`left`)
    self.top = try container.decode(Swift.Float.self, forKey: .top)
    self.`right` = try container.decode(Swift.Float.self, forKey: .`right`)
    self.bottom = try container.decode(Swift.Float.self, forKey: .bottom)
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.`left`, forKey: .`left`)
    try container.encode(self.top, forKey: .top)
    try container.encode(self.`right`, forKey: .`right`)
    try container.encode(self.bottom, forKey: .bottom)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.NormalizedBoundingBox"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
