// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Normalized bounding box.
/// The normalized vertex coordinates are relative to the original image.
/// Range: [0, 1].
public struct NormalizedBoundingBox: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Left X coordinate.
  public var `left`: Swift.Float = Swift.Float()

  /// Top Y coordinate.
  public var top: Swift.Float = Swift.Float()

  /// Right X coordinate.
  public var `right`: Swift.Float = Swift.Float()

  /// Bottom Y coordinate.
  public var bottom: Swift.Float = Swift.Float()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `NormalizedBoundingBox`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NormalizedBoundingBox().with { $0.`left` = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let `left` = CodingKeys(stringValue: "left")
    static let top = CodingKeys(stringValue: "top")
    static let `right` = CodingKeys(stringValue: "right")
    static let bottom = CodingKeys(stringValue: "bottom")

    static let _knownKeys: Set<Swift.String> = [
      "left",
      "top",
      "right",
      "bottom",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .`left`) {
      self.`left` = value
    }
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .top) {
      self.top = value
    }
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .`right`) {
      self.`right` = value
    }
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .bottom) {
      self.bottom = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.`left`, forKey: .`left`)
    try container.encode(self.top, forKey: .top)
    try container.encode(self.`right`, forKey: .`right`)
    try container.encode(self.bottom, forKey: .bottom)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.NormalizedBoundingBox"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
