// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Annotations corresponding to one tracked object.
public struct ObjectTrackingAnnotation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Entity to specify the object category that this track is labeled as.
  public var entity: Entity? = nil

  /// Object category's labeling confidence of this track.
  public var confidence: Swift.Float = Swift.Float()

  /// Information corresponding to all frames where this object track appears.
  /// Non-streaming batch mode: it may be one or multiple ObjectTrackingFrame
  /// messages in frames.
  /// Streaming mode: it can only be one ObjectTrackingFrame message in frames.
  public var frames: [ObjectTrackingFrame] = []

  /// Feature version.
  public var version: Swift.String = Swift.String()

  /// Different representation of tracking info in non-streaming batch
  /// and streaming modes.
  public var trackInfo: OneOf_TrackInfo? = nil

  /// Initialize a new instance of `ObjectTrackingAnnotation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ObjectTrackingAnnotation().with { $0.segment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case segment = "segment"
    case trackId = "trackId"
    case entity = "entity"
    case confidence = "confidence"
    case frames = "frames"
    case version = "version"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.entity = try container.decodeIfPresent(Entity.self, forKey: .entity)
    self.confidence = try container.decode(Swift.Float.self, forKey: .confidence)
    self.frames = try container.decode([ObjectTrackingFrame].self, forKey: .frames)
    self.version = try container.decode(Swift.String.self, forKey: .version)

    var trackInfo: OneOf_TrackInfo? = nil
    let trackInfoCheckAndSet = {
      if trackInfo != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'trackInfo'"))
      }
      trackInfo = $0
    }
    if let segment = try container.decodeIfPresent(VideoSegment?.self, forKey: .segment) {
      try trackInfoCheckAndSet(.segment(segment))
    }
    if let trackId = try container.decodeIfPresent(Swift.Int64.self, forKey: .trackId) {
      try trackInfoCheckAndSet(.trackId(trackId))
    }
    self.trackInfo = trackInfo
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.entity, forKey: .entity)
    try container.encode(self.confidence, forKey: .confidence)
    try container.encode(self.frames, forKey: .frames)
    try container.encode(self.version, forKey: .version)

    if let choice = self.trackInfo {
      switch choice {
      case .segment(let value):
        try container.encode(value, forKey: .segment)
      case .trackId(let value):
        try container.encode(value, forKey: .trackId)
      }
    }
  }

  /// Different representation of tracking info in non-streaming batch
  /// and streaming modes.
  public enum OneOf_TrackInfo: Codable, Equatable, Sendable {
    /// Non-streaming batch mode ONLY.
    /// Each object track corresponds to one video segment where it appears.
    indirect case segment(VideoSegment?)
    /// Streaming mode ONLY.
    /// In streaming mode, we do not know the end time of a tracked object
    /// before it is completed. Hence, there is no VideoSegment info returned.
    /// Instead, we provide a unique identifiable integer track_id so that
    /// the customers can correlate the results of the ongoing
    /// ObjectTrackAnnotation of the same track_id over time.
    case trackId(Swift.Int64)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.ObjectTrackingAnnotation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
