// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Video frame level annotations for object detection and tracking. This field
/// stores per frame location, time offset, and confidence.
public struct ObjectTrackingFrame: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The normalized bounding box location of this object track for the frame.
  public var normalizedBoundingBox: NormalizedBoundingBox? = nil

  /// The timestamp of the frame in microseconds.
  public var timeOffset: GoogleWKT.Duration? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ObjectTrackingFrame`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ObjectTrackingFrame().with { $0.normalizedBoundingBox = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let normalizedBoundingBox = CodingKeys(stringValue: "normalizedBoundingBox")
    static let timeOffset = CodingKeys(stringValue: "timeOffset")

    static let _knownKeys: Set<Swift.String> = [
      "normalizedBoundingBox",
      "timeOffset",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.normalizedBoundingBox = try container.decodeIfPresent(
      NormalizedBoundingBox.self, forKey: .normalizedBoundingBox)
    self.timeOffset = try container.decodeIfPresent(GoogleWKT.Duration.self, forKey: .timeOffset)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.normalizedBoundingBox, forKey: .normalizedBoundingBox)
    try container.encodeIfPresent(self.timeOffset, forKey: .timeOffset)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.ObjectTrackingFrame"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
