// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Config for PERSON_DETECTION.
public struct PersonDetectionConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Whether bounding boxes are included in the person detection annotation
  /// output.
  public var includeBoundingBoxes: Swift.Bool = Swift.Bool()

  /// Whether to enable pose landmarks detection. Ignored if
  /// 'include_bounding_boxes' is set to false.
  public var includePoseLandmarks: Swift.Bool = Swift.Bool()

  /// Whether to enable person attributes detection, such as cloth color (black,
  /// blue, etc), type (coat, dress, etc), pattern (plain, floral, etc), hair,
  /// etc.
  /// Ignored if 'include_bounding_boxes' is set to false.
  public var includeAttributes: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `PersonDetectionConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PersonDetectionConfig().with { $0.includeBoundingBoxes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.PersonDetectionConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
