// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Config for SPEECH_TRANSCRIPTION.
public struct SpeechTranscriptionConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. *Required* The language of the supplied audio as a
  /// [BCP-47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt) language tag.
  /// Example: "en-US".
  /// See [Language Support](https://cloud.google.com/speech/docs/languages)
  /// for a list of the currently supported language codes.
  public var languageCode: Swift.String = Swift.String()

  /// Optional. Maximum number of recognition hypotheses to be returned.
  /// Specifically, the maximum number of `SpeechRecognitionAlternative` messages
  /// within each `SpeechTranscription`. The server may return fewer than
  /// `max_alternatives`. Valid values are `0`-`30`. A value of `0` or `1` will
  /// return a maximum of one. If omitted, will return a maximum of one.
  public var maxAlternatives: Swift.Int32 = Swift.Int32()

  /// Optional. If set to `true`, the server will attempt to filter out
  /// profanities, replacing all but the initial character in each filtered word
  /// with asterisks, e.g. "f***". If set to `false` or omitted, profanities
  /// won't be filtered out.
  public var filterProfanity: Swift.Bool = Swift.Bool()

  /// Optional. A means to provide context to assist the speech recognition.
  public var speechContexts: [SpeechContext] = []

  /// Optional. If 'true', adds punctuation to recognition result hypotheses.
  /// This feature is only available in select languages. Setting this for
  /// requests in other languages has no effect at all. The default 'false' value
  /// does not add punctuation to result hypotheses. NOTE: "This is currently
  /// offered as an experimental service, complimentary to all users. In the
  /// future this may be exclusively available as a premium feature."
  public var enableAutomaticPunctuation: Swift.Bool = Swift.Bool()

  /// Optional. For file formats, such as MXF or MKV, supporting multiple audio
  /// tracks, specify up to two tracks. Default: track 0.
  public var audioTracks: [Swift.Int32] = []

  /// Optional. If 'true', enables speaker detection for each recognized word in
  /// the top alternative of the recognition result using a speaker_tag provided
  /// in the WordInfo.
  /// Note: When this is true, we send all the words from the beginning of the
  /// audio for the top alternative in every consecutive response.
  /// This is done in order to improve our speaker tags as our models learn to
  /// identify the speakers in the conversation over time.
  public var enableSpeakerDiarization: Swift.Bool = Swift.Bool()

  /// Optional. If set, specifies the estimated number of speakers in the
  /// conversation. If not set, defaults to '2'. Ignored unless
  /// enable_speaker_diarization is set to true.
  public var diarizationSpeakerCount: Swift.Int32 = Swift.Int32()

  /// Optional. If `true`, the top result includes a list of words and the
  /// confidence for those words. If `false`, no word-level confidence
  /// information is returned. The default is `false`.
  public var enableWordConfidence: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SpeechTranscriptionConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SpeechTranscriptionConfig().with { $0.languageCode = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let languageCode = CodingKeys(stringValue: "languageCode")
    static let maxAlternatives = CodingKeys(stringValue: "maxAlternatives")
    static let filterProfanity = CodingKeys(stringValue: "filterProfanity")
    static let speechContexts = CodingKeys(stringValue: "speechContexts")
    static let enableAutomaticPunctuation = CodingKeys(stringValue: "enableAutomaticPunctuation")
    static let audioTracks = CodingKeys(stringValue: "audioTracks")
    static let enableSpeakerDiarization = CodingKeys(stringValue: "enableSpeakerDiarization")
    static let diarizationSpeakerCount = CodingKeys(stringValue: "diarizationSpeakerCount")
    static let enableWordConfidence = CodingKeys(stringValue: "enableWordConfidence")

    static let _knownKeys: Set<Swift.String> = [
      "languageCode",
      "maxAlternatives",
      "filterProfanity",
      "speechContexts",
      "enableAutomaticPunctuation",
      "audioTracks",
      "enableSpeakerDiarization",
      "diarizationSpeakerCount",
      "enableWordConfidence",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .languageCode) {
      self.languageCode = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxAlternatives) {
      self.maxAlternatives = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .filterProfanity) {
      self.filterProfanity = value
    }
    if let value = try container.decodeIfPresent([SpeechContext].self, forKey: .speechContexts) {
      self.speechContexts = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .enableAutomaticPunctuation)
    {
      self.enableAutomaticPunctuation = value
    }
    if let value = try container.decodeIfPresent([Swift.Int32].self, forKey: .audioTracks) {
      self.audioTracks = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableSpeakerDiarization)
    {
      self.enableSpeakerDiarization = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .diarizationSpeakerCount)
    {
      self.diarizationSpeakerCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableWordConfidence) {
      self.enableWordConfidence = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.languageCode, forKey: .languageCode)
    try container.encode(self.maxAlternatives, forKey: .maxAlternatives)
    try container.encode(self.filterProfanity, forKey: .filterProfanity)
    try container.encode(self.speechContexts, forKey: .speechContexts)
    try container.encode(self.enableAutomaticPunctuation, forKey: .enableAutomaticPunctuation)
    try container.encode(self.audioTracks, forKey: .audioTracks)
    try container.encode(self.enableSpeakerDiarization, forKey: .enableSpeakerDiarization)
    try container.encode(self.diarizationSpeakerCount, forKey: .diarizationSpeakerCount)
    try container.encode(self.enableWordConfidence, forKey: .enableWordConfidence)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.SpeechTranscriptionConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
