// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// For tracking related features.
/// An object at time_offset with attributes, and located with
/// normalized_bounding_box.
public struct TimestampedObject: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Normalized Bounding box in a frame, where the object is located.
  public var normalizedBoundingBox: NormalizedBoundingBox? = nil

  /// Time-offset, relative to the beginning of the video,
  /// corresponding to the video frame for this object.
  public var timeOffset: GoogleCloudWKT.Duration? = nil

  /// Optional. The attributes of the object in the bounding box.
  public var attributes: [DetectedAttribute] = []

  /// Optional. The detected landmarks.
  public var landmarks: [DetectedLandmark] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `TimestampedObject`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TimestampedObject().with { $0.normalizedBoundingBox = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let normalizedBoundingBox = CodingKeys(stringValue: "normalizedBoundingBox")
    static let timeOffset = CodingKeys(stringValue: "timeOffset")
    static let attributes = CodingKeys(stringValue: "attributes")
    static let landmarks = CodingKeys(stringValue: "landmarks")

    static let _knownKeys: Set<Swift.String> = [
      "normalizedBoundingBox",
      "timeOffset",
      "attributes",
      "landmarks",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.normalizedBoundingBox = try container.decodeIfPresent(
      NormalizedBoundingBox.self, forKey: .normalizedBoundingBox)
    self.timeOffset = try container.decodeIfPresent(
      GoogleCloudWKT.Duration.self, forKey: .timeOffset)
    if let value = try container.decodeIfPresent([DetectedAttribute].self, forKey: .attributes) {
      self.attributes = value
    }
    if let value = try container.decodeIfPresent([DetectedLandmark].self, forKey: .landmarks) {
      self.landmarks = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.normalizedBoundingBox, forKey: .normalizedBoundingBox)
    try container.encodeIfPresent(self.timeOffset, forKey: .timeOffset)
    try container.encode(self.attributes, forKey: .attributes)
    try container.encode(self.landmarks, forKey: .landmarks)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.TimestampedObject"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
