// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// For tracking related features.
/// An object at time_offset with attributes, and located with
/// normalized_bounding_box.
public struct TimestampedObject: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Normalized Bounding box in a frame, where the object is located.
  public var normalizedBoundingBox: NormalizedBoundingBox? = nil

  /// Time-offset, relative to the beginning of the video,
  /// corresponding to the video frame for this object.
  public var timeOffset: GoogleCloudWkt.Duration? = nil

  /// Optional. The attributes of the object in the bounding box.
  public var attributes: [DetectedAttribute] = []

  /// Optional. The detected landmarks.
  public var landmarks: [DetectedLandmark] = []

  /// Initialize a new instance of `TimestampedObject`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TimestampedObject().with { $0.normalizedBoundingBox = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.TimestampedObject"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
