// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A track of an object instance.
public struct Track: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Video segment of a track.
  public var segment: VideoSegment? = nil

  /// The object with timestamp and attributes per frame in the track.
  public var timestampedObjects: [TimestampedObject] = []

  /// Optional. Attributes in the track level.
  public var attributes: [DetectedAttribute] = []

  /// Optional. The confidence score of the tracked object.
  public var confidence: Swift.Float = Swift.Float()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Track`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Track().with { $0.segment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let segment = CodingKeys(stringValue: "segment")
    static let timestampedObjects = CodingKeys(stringValue: "timestampedObjects")
    static let attributes = CodingKeys(stringValue: "attributes")
    static let confidence = CodingKeys(stringValue: "confidence")

    static let _knownKeys: Set<Swift.String> = [
      "segment",
      "timestampedObjects",
      "attributes",
      "confidence",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.segment = try container.decodeIfPresent(VideoSegment.self, forKey: .segment)
    if let value = try container.decodeIfPresent(
      [TimestampedObject].self, forKey: .timestampedObjects)
    {
      self.timestampedObjects = value
    }
    if let value = try container.decodeIfPresent([DetectedAttribute].self, forKey: .attributes) {
      self.attributes = value
    }
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .confidence) {
      self.confidence = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.segment, forKey: .segment)
    try container.encode(self.timestampedObjects, forKey: .timestampedObjects)
    try container.encode(self.attributes, forKey: .attributes)
    try container.encode(self.confidence, forKey: .confidence)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.Track"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
