// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Video segment.
public struct VideoSegment: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Time-offset, relative to the beginning of the video,
  /// corresponding to the start of the segment (inclusive).
  public var startTimeOffset: GoogleWKT.WKTDuration? = nil

  /// Time-offset, relative to the beginning of the video,
  /// corresponding to the end of the segment (inclusive).
  public var endTimeOffset: GoogleWKT.WKTDuration? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `VideoSegment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VideoSegment().with { $0.startTimeOffset = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let startTimeOffset = CodingKeys(stringValue: "startTimeOffset")
    static let endTimeOffset = CodingKeys(stringValue: "endTimeOffset")

    static let _knownKeys: Set<Swift.String> = [
      "startTimeOffset",
      "endTimeOffset",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.startTimeOffset = try container.decodeIfPresent(
      GoogleWKT.WKTDuration.self, forKey: .startTimeOffset)
    self.endTimeOffset = try container.decodeIfPresent(
      GoogleWKT.WKTDuration.self, forKey: .endTimeOffset)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.startTimeOffset, forKey: .startTimeOffset)
    try container.encodeIfPresent(self.endTimeOffset, forKey: .endTimeOffset)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.VideoSegment"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
