// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Video context and/or feature-specific parameters.
public struct VideoContext: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Video segments to annotate. The segments may overlap and are not required
  /// to be contiguous or span the whole video. If unspecified, each video is
  /// treated as a single segment.
  public var segments: [VideoSegment] = []

  /// Config for LABEL_DETECTION.
  public var labelDetectionConfig: LabelDetectionConfig? = nil

  /// Config for SHOT_CHANGE_DETECTION.
  public var shotChangeDetectionConfig: ShotChangeDetectionConfig? = nil

  /// Config for EXPLICIT_CONTENT_DETECTION.
  public var explicitContentDetectionConfig: ExplicitContentDetectionConfig? = nil

  /// Config for FACE_DETECTION.
  public var faceDetectionConfig: FaceDetectionConfig? = nil

  /// Config for SPEECH_TRANSCRIPTION.
  public var speechTranscriptionConfig: SpeechTranscriptionConfig? = nil

  /// Config for TEXT_DETECTION.
  public var textDetectionConfig: TextDetectionConfig? = nil

  /// Config for PERSON_DETECTION.
  public var personDetectionConfig: PersonDetectionConfig? = nil

  /// Config for OBJECT_TRACKING.
  public var objectTrackingConfig: ObjectTrackingConfig? = nil

  /// Initialize a new instance of `VideoContext`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VideoContext().with { $0.segments = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.VideoContext"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
