// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Video context and/or feature-specific parameters.
public struct VideoContext: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Video segments to annotate. The segments may overlap and are not required
  /// to be contiguous or span the whole video. If unspecified, each video is
  /// treated as a single segment.
  public var segments: [VideoSegment] = []

  /// Config for LABEL_DETECTION.
  public var labelDetectionConfig: LabelDetectionConfig? = nil

  /// Config for SHOT_CHANGE_DETECTION.
  public var shotChangeDetectionConfig: ShotChangeDetectionConfig? = nil

  /// Config for EXPLICIT_CONTENT_DETECTION.
  public var explicitContentDetectionConfig: ExplicitContentDetectionConfig? = nil

  /// Config for FACE_DETECTION.
  public var faceDetectionConfig: FaceDetectionConfig? = nil

  /// Config for SPEECH_TRANSCRIPTION.
  public var speechTranscriptionConfig: SpeechTranscriptionConfig? = nil

  /// Config for TEXT_DETECTION.
  public var textDetectionConfig: TextDetectionConfig? = nil

  /// Config for PERSON_DETECTION.
  public var personDetectionConfig: PersonDetectionConfig? = nil

  /// Config for OBJECT_TRACKING.
  public var objectTrackingConfig: ObjectTrackingConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `VideoContext`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VideoContext().with { $0.segments = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let segments = CodingKeys(stringValue: "segments")
    static let labelDetectionConfig = CodingKeys(stringValue: "labelDetectionConfig")
    static let shotChangeDetectionConfig = CodingKeys(stringValue: "shotChangeDetectionConfig")
    static let explicitContentDetectionConfig = CodingKeys(
      stringValue: "explicitContentDetectionConfig")
    static let faceDetectionConfig = CodingKeys(stringValue: "faceDetectionConfig")
    static let speechTranscriptionConfig = CodingKeys(stringValue: "speechTranscriptionConfig")
    static let textDetectionConfig = CodingKeys(stringValue: "textDetectionConfig")
    static let personDetectionConfig = CodingKeys(stringValue: "personDetectionConfig")
    static let objectTrackingConfig = CodingKeys(stringValue: "objectTrackingConfig")

    static let _knownKeys: Set<Swift.String> = [
      "segments",
      "labelDetectionConfig",
      "shotChangeDetectionConfig",
      "explicitContentDetectionConfig",
      "faceDetectionConfig",
      "speechTranscriptionConfig",
      "textDetectionConfig",
      "personDetectionConfig",
      "objectTrackingConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([VideoSegment].self, forKey: .segments) {
      self.segments = value
    }
    self.labelDetectionConfig = try container.decodeIfPresent(
      LabelDetectionConfig.self, forKey: .labelDetectionConfig)
    self.shotChangeDetectionConfig = try container.decodeIfPresent(
      ShotChangeDetectionConfig.self, forKey: .shotChangeDetectionConfig)
    self.explicitContentDetectionConfig = try container.decodeIfPresent(
      ExplicitContentDetectionConfig.self, forKey: .explicitContentDetectionConfig)
    self.faceDetectionConfig = try container.decodeIfPresent(
      FaceDetectionConfig.self, forKey: .faceDetectionConfig)
    self.speechTranscriptionConfig = try container.decodeIfPresent(
      SpeechTranscriptionConfig.self, forKey: .speechTranscriptionConfig)
    self.textDetectionConfig = try container.decodeIfPresent(
      TextDetectionConfig.self, forKey: .textDetectionConfig)
    self.personDetectionConfig = try container.decodeIfPresent(
      PersonDetectionConfig.self, forKey: .personDetectionConfig)
    self.objectTrackingConfig = try container.decodeIfPresent(
      ObjectTrackingConfig.self, forKey: .objectTrackingConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.segments, forKey: .segments)
    try container.encodeIfPresent(self.labelDetectionConfig, forKey: .labelDetectionConfig)
    try container.encodeIfPresent(
      self.shotChangeDetectionConfig, forKey: .shotChangeDetectionConfig)
    try container.encodeIfPresent(
      self.explicitContentDetectionConfig, forKey: .explicitContentDetectionConfig)
    try container.encodeIfPresent(self.faceDetectionConfig, forKey: .faceDetectionConfig)
    try container.encodeIfPresent(
      self.speechTranscriptionConfig, forKey: .speechTranscriptionConfig)
    try container.encodeIfPresent(self.textDetectionConfig, forKey: .textDetectionConfig)
    try container.encodeIfPresent(self.personDetectionConfig, forKey: .personDetectionConfig)
    try container.encodeIfPresent(self.objectTrackingConfig, forKey: .objectTrackingConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.VideoContext"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
