// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Annotation progress for a single video.
public struct VideoAnnotationProgress: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Video file location in
  /// [Cloud Storage](https://cloud.google.com/storage/).
  public var inputUri: Swift.String = Swift.String()

  /// Approximate percentage processed thus far. Guaranteed to be
  /// 100 when fully processed.
  public var progressPercent: Swift.Int32 = Swift.Int32()

  /// Time when the request was received.
  public var startTime: GoogleWKT.WKTTimestamp? = nil

  /// Time of the most recent update.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Specifies which feature is being tracked if the request contains more than
  /// one feature.
  public var feature: Feature = Feature()

  /// Specifies which segment is being tracked if the request contains more than
  /// one segment.
  public var segment: VideoSegment? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `VideoAnnotationProgress`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VideoAnnotationProgress().with { $0.inputUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let inputUri = CodingKeys(stringValue: "inputUri")
    static let progressPercent = CodingKeys(stringValue: "progressPercent")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let feature = CodingKeys(stringValue: "feature")
    static let segment = CodingKeys(stringValue: "segment")

    static let _knownKeys: Set<Swift.String> = [
      "inputUri",
      "progressPercent",
      "startTime",
      "updateTime",
      "feature",
      "segment",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inputUri) {
      self.inputUri = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .progressPercent) {
      self.progressPercent = value
    }
    self.startTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .startTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Feature.self, forKey: .feature) {
      self.feature = value
    }
    self.segment = try container.decodeIfPresent(VideoSegment.self, forKey: .segment)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.inputUri, forKey: .inputUri)
    try container.encode(self.progressPercent, forKey: .progressPercent)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.feature, forKey: .feature)
    try container.encodeIfPresent(self.segment, forKey: .segment)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.VideoAnnotationProgress"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
