// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Annotation progress for a single video.
public struct VideoAnnotationProgress: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Video file location in
  /// [Cloud Storage](https://cloud.google.com/storage/).
  public var inputUri: Swift.String = Swift.String()

  /// Approximate percentage processed thus far. Guaranteed to be
  /// 100 when fully processed.
  public var progressPercent: Swift.Int32 = Swift.Int32()

  /// Time when the request was received.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// Time of the most recent update.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Specifies which feature is being tracked if the request contains more than
  /// one feature.
  public var feature: Feature = Feature()

  /// Specifies which segment is being tracked if the request contains more than
  /// one segment.
  public var segment: VideoSegment? = nil

  /// Initialize a new instance of `VideoAnnotationProgress`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VideoAnnotationProgress().with { $0.inputUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.VideoAnnotationProgress"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
