// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc

/// Annotation results for a single video.
public struct VideoAnnotationResults: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Video file location in
  /// [Cloud Storage](https://cloud.google.com/storage/).
  public var inputUri: Swift.String = Swift.String()

  /// Video segment on which the annotation is run.
  public var segment: VideoSegment? = nil

  /// Topical label annotations on video level or user-specified segment level.
  /// There is exactly one element for each unique label.
  public var segmentLabelAnnotations: [LabelAnnotation] = []

  /// Presence label annotations on video level or user-specified segment level.
  /// There is exactly one element for each unique label. Compared to the
  /// existing topical `segment_label_annotations`, this field presents more
  /// fine-grained, segment-level labels detected in video content and is made
  /// available only when the client sets `LabelDetectionConfig.model` to
  /// "builtin/latest" in the request.
  public var segmentPresenceLabelAnnotations: [LabelAnnotation] = []

  /// Topical label annotations on shot level.
  /// There is exactly one element for each unique label.
  public var shotLabelAnnotations: [LabelAnnotation] = []

  /// Presence label annotations on shot level. There is exactly one element for
  /// each unique label. Compared to the existing topical
  /// `shot_label_annotations`, this field presents more fine-grained, shot-level
  /// labels detected in video content and is made available only when the client
  /// sets `LabelDetectionConfig.model` to "builtin/latest" in the request.
  public var shotPresenceLabelAnnotations: [LabelAnnotation] = []

  /// Label annotations on frame level.
  /// There is exactly one element for each unique label.
  public var frameLabelAnnotations: [LabelAnnotation] = []

  /// Deprecated. Please use `face_detection_annotations` instead.
  @available(*, deprecated)
  public var faceAnnotations: [FaceAnnotation] = []

  /// Face detection annotations.
  public var faceDetectionAnnotations: [FaceDetectionAnnotation] = []

  /// Shot annotations. Each shot is represented as a video segment.
  public var shotAnnotations: [VideoSegment] = []

  /// Explicit content annotation.
  public var explicitAnnotation: ExplicitContentAnnotation? = nil

  /// Speech transcription.
  public var speechTranscriptions: [SpeechTranscription] = []

  /// OCR text detection and tracking.
  /// Annotations for list of detected text snippets. Each will have list of
  /// frame information associated with it.
  public var textAnnotations: [TextAnnotation] = []

  /// Annotations for list of objects detected and tracked in video.
  public var objectAnnotations: [ObjectTrackingAnnotation] = []

  /// Annotations for list of logos detected, tracked and recognized in video.
  public var logoRecognitionAnnotations: [LogoRecognitionAnnotation] = []

  /// Person detection annotations.
  public var personDetectionAnnotations: [PersonDetectionAnnotation] = []

  /// If set, indicates an error. Note that for a single `AnnotateVideoRequest`
  /// some videos may succeed and some may fail.
  public var error: GoogleRpc.Status? = nil

  /// Initialize a new instance of `VideoAnnotationResults`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VideoAnnotationResults().with { $0.inputUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.VideoAnnotationResults"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
