// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// Annotation results for a single video.
public struct VideoAnnotationResults: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Video file location in
  /// [Cloud Storage](https://cloud.google.com/storage/).
  public var inputUri: Swift.String = Swift.String()

  /// Video segment on which the annotation is run.
  public var segment: VideoSegment? = nil

  /// Topical label annotations on video level or user-specified segment level.
  /// There is exactly one element for each unique label.
  public var segmentLabelAnnotations: [LabelAnnotation] = []

  /// Presence label annotations on video level or user-specified segment level.
  /// There is exactly one element for each unique label. Compared to the
  /// existing topical `segment_label_annotations`, this field presents more
  /// fine-grained, segment-level labels detected in video content and is made
  /// available only when the client sets `LabelDetectionConfig.model` to
  /// "builtin/latest" in the request.
  public var segmentPresenceLabelAnnotations: [LabelAnnotation] = []

  /// Topical label annotations on shot level.
  /// There is exactly one element for each unique label.
  public var shotLabelAnnotations: [LabelAnnotation] = []

  /// Presence label annotations on shot level. There is exactly one element for
  /// each unique label. Compared to the existing topical
  /// `shot_label_annotations`, this field presents more fine-grained, shot-level
  /// labels detected in video content and is made available only when the client
  /// sets `LabelDetectionConfig.model` to "builtin/latest" in the request.
  public var shotPresenceLabelAnnotations: [LabelAnnotation] = []

  /// Label annotations on frame level.
  /// There is exactly one element for each unique label.
  public var frameLabelAnnotations: [LabelAnnotation] = []

  /// Deprecated. Please use `face_detection_annotations` instead.
  @available(*, deprecated)
  public var faceAnnotations: [FaceAnnotation] = []

  /// Face detection annotations.
  public var faceDetectionAnnotations: [FaceDetectionAnnotation] = []

  /// Shot annotations. Each shot is represented as a video segment.
  public var shotAnnotations: [VideoSegment] = []

  /// Explicit content annotation.
  public var explicitAnnotation: ExplicitContentAnnotation? = nil

  /// Speech transcription.
  public var speechTranscriptions: [SpeechTranscription] = []

  /// OCR text detection and tracking.
  /// Annotations for list of detected text snippets. Each will have list of
  /// frame information associated with it.
  public var textAnnotations: [TextAnnotation] = []

  /// Annotations for list of objects detected and tracked in video.
  public var objectAnnotations: [ObjectTrackingAnnotation] = []

  /// Annotations for list of logos detected, tracked and recognized in video.
  public var logoRecognitionAnnotations: [LogoRecognitionAnnotation] = []

  /// Person detection annotations.
  public var personDetectionAnnotations: [PersonDetectionAnnotation] = []

  /// If set, indicates an error. Note that for a single `AnnotateVideoRequest`
  /// some videos may succeed and some may fail.
  public var error: GoogleRpc.Status? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `VideoAnnotationResults`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VideoAnnotationResults().with { $0.inputUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let inputUri = CodingKeys(stringValue: "inputUri")
    static let segment = CodingKeys(stringValue: "segment")
    static let segmentLabelAnnotations = CodingKeys(stringValue: "segmentLabelAnnotations")
    static let segmentPresenceLabelAnnotations = CodingKeys(
      stringValue: "segmentPresenceLabelAnnotations")
    static let shotLabelAnnotations = CodingKeys(stringValue: "shotLabelAnnotations")
    static let shotPresenceLabelAnnotations = CodingKeys(
      stringValue: "shotPresenceLabelAnnotations")
    static let frameLabelAnnotations = CodingKeys(stringValue: "frameLabelAnnotations")
    static let faceAnnotations = CodingKeys(stringValue: "faceAnnotations")
    static let faceDetectionAnnotations = CodingKeys(stringValue: "faceDetectionAnnotations")
    static let shotAnnotations = CodingKeys(stringValue: "shotAnnotations")
    static let explicitAnnotation = CodingKeys(stringValue: "explicitAnnotation")
    static let speechTranscriptions = CodingKeys(stringValue: "speechTranscriptions")
    static let textAnnotations = CodingKeys(stringValue: "textAnnotations")
    static let objectAnnotations = CodingKeys(stringValue: "objectAnnotations")
    static let logoRecognitionAnnotations = CodingKeys(stringValue: "logoRecognitionAnnotations")
    static let personDetectionAnnotations = CodingKeys(stringValue: "personDetectionAnnotations")
    static let error = CodingKeys(stringValue: "error")

    static let _knownKeys: Set<Swift.String> = [
      "inputUri",
      "segment",
      "segmentLabelAnnotations",
      "segmentPresenceLabelAnnotations",
      "shotLabelAnnotations",
      "shotPresenceLabelAnnotations",
      "frameLabelAnnotations",
      "faceAnnotations",
      "faceDetectionAnnotations",
      "shotAnnotations",
      "explicitAnnotation",
      "speechTranscriptions",
      "textAnnotations",
      "objectAnnotations",
      "logoRecognitionAnnotations",
      "personDetectionAnnotations",
      "error",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inputUri) {
      self.inputUri = value
    }
    self.segment = try container.decodeIfPresent(VideoSegment.self, forKey: .segment)
    if let value = try container.decodeIfPresent(
      [LabelAnnotation].self, forKey: .segmentLabelAnnotations)
    {
      self.segmentLabelAnnotations = value
    }
    if let value = try container.decodeIfPresent(
      [LabelAnnotation].self, forKey: .segmentPresenceLabelAnnotations)
    {
      self.segmentPresenceLabelAnnotations = value
    }
    if let value = try container.decodeIfPresent(
      [LabelAnnotation].self, forKey: .shotLabelAnnotations)
    {
      self.shotLabelAnnotations = value
    }
    if let value = try container.decodeIfPresent(
      [LabelAnnotation].self, forKey: .shotPresenceLabelAnnotations)
    {
      self.shotPresenceLabelAnnotations = value
    }
    if let value = try container.decodeIfPresent(
      [LabelAnnotation].self, forKey: .frameLabelAnnotations)
    {
      self.frameLabelAnnotations = value
    }
    if let value = try container.decodeIfPresent([FaceAnnotation].self, forKey: .faceAnnotations) {
      self.faceAnnotations = value
    }
    if let value = try container.decodeIfPresent(
      [FaceDetectionAnnotation].self, forKey: .faceDetectionAnnotations)
    {
      self.faceDetectionAnnotations = value
    }
    if let value = try container.decodeIfPresent([VideoSegment].self, forKey: .shotAnnotations) {
      self.shotAnnotations = value
    }
    self.explicitAnnotation = try container.decodeIfPresent(
      ExplicitContentAnnotation.self, forKey: .explicitAnnotation)
    if let value = try container.decodeIfPresent(
      [SpeechTranscription].self, forKey: .speechTranscriptions)
    {
      self.speechTranscriptions = value
    }
    if let value = try container.decodeIfPresent([TextAnnotation].self, forKey: .textAnnotations) {
      self.textAnnotations = value
    }
    if let value = try container.decodeIfPresent(
      [ObjectTrackingAnnotation].self, forKey: .objectAnnotations)
    {
      self.objectAnnotations = value
    }
    if let value = try container.decodeIfPresent(
      [LogoRecognitionAnnotation].self, forKey: .logoRecognitionAnnotations)
    {
      self.logoRecognitionAnnotations = value
    }
    if let value = try container.decodeIfPresent(
      [PersonDetectionAnnotation].self, forKey: .personDetectionAnnotations)
    {
      self.personDetectionAnnotations = value
    }
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.inputUri, forKey: .inputUri)
    try container.encodeIfPresent(self.segment, forKey: .segment)
    try container.encode(self.segmentLabelAnnotations, forKey: .segmentLabelAnnotations)
    try container.encode(
      self.segmentPresenceLabelAnnotations, forKey: .segmentPresenceLabelAnnotations)
    try container.encode(self.shotLabelAnnotations, forKey: .shotLabelAnnotations)
    try container.encode(self.shotPresenceLabelAnnotations, forKey: .shotPresenceLabelAnnotations)
    try container.encode(self.frameLabelAnnotations, forKey: .frameLabelAnnotations)
    try container.encode(self.faceAnnotations, forKey: .faceAnnotations)
    try container.encode(self.faceDetectionAnnotations, forKey: .faceDetectionAnnotations)
    try container.encode(self.shotAnnotations, forKey: .shotAnnotations)
    try container.encodeIfPresent(self.explicitAnnotation, forKey: .explicitAnnotation)
    try container.encode(self.speechTranscriptions, forKey: .speechTranscriptions)
    try container.encode(self.textAnnotations, forKey: .textAnnotations)
    try container.encode(self.objectAnnotations, forKey: .objectAnnotations)
    try container.encode(self.logoRecognitionAnnotations, forKey: .logoRecognitionAnnotations)
    try container.encode(self.personDetectionAnnotations, forKey: .personDetectionAnnotations)
    try container.encodeIfPresent(self.error, forKey: .error)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.videointelligence.v1.VideoAnnotationResults"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
